version: '3.3'

services:
  be:
    build:
      context: ./../
      dockerfile: Dockerfile
    container_name: cloud-storage-be
    ports: [ '8080:8080' ]
    depends_on: ['db']
    restart: always
    volumes:
      - ./../:/app
      # - ~/docker-volumes/skeleton/be/node_modules:/app/node_modules
    environment:
      TZ: Europe/Kiev
      MODE: application
    command: sh -c "npm i && npm run migration:db && npm run nodemon"
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin --disable-log-bin
    restart: always
    ports: [ '3306:3306' ]
    environment:
      MYSQL_DATABASE: cloud-storage
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: strong-password
      TZ: Europe/Kiev
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    container_name: cloud-storage-db
    volumes:
      - ~/docker-volumes/cloud-storage/db:/var/lib/mysql
